#!/usr/bin/env bash

# magick_montage
#
# Description: Uses ImageMagick montage to make a cool collage.
# Author: demingongo
# Link: https://github.com/demingongo
# Availability: ?

img_nbr=5

int_re='^[0-9]+$'

if [ $# -gt 0 ]; then
	if [ -n "$2" ]; then
		echo "fdfdf"
		if ! [[ $2 =~ $int_re ]]; then
			echo "error: arg 2 is not a number"
			exit 1
		else
			if [[ $2 -gt 0 ]] && [[ $2 -lt $img_nbr ]]; then
				img_nbr="$2"
			fi
		fi
	fi
else
	echo "error: missing output"
	exit 1
fi

gum style \
	--foreground 212 --border-foreground 212 --border double \
	--align center --width 50 --margin "1 2" --padding "2 4" \
	'magick_montage: Uses ImageMagick montage to make a cool collage'

echo "Select max ${img_nbr} images (q to validate):"

search_path="$HOME/Pictures"

FILES=""
nb_files=0

for (( i=1; i<=$img_nbr; i++ ))
do
	filepath=`gum file $search_path`
	if [[ -z "$filepath" ]]; then
		break
	fi
	FILES="${FILES}\"${filepath}\" "
	nb_files=$((nb_files + 1))
	echo "$filepath"
	search_path=`dirname "$filepath"`
done

if [[ -z $FILES ]]; then
	echo "No files selected"
	exit
fi

bg_opt="background"
bg_value='white'
bg_type=`gum choose {'color','image'}`

if [ "$bg_type" = 'image' ]; then
	bg_opt="texture"
	tmp_bg_value=`gum file $search_path`
	bg_value="\"${tmp_bg_value}\""
else
	bg_value=`gum input`
	bg_value="'$bg_value'"
fi

MONTAGE_CMD="montage -${bg_opt} ${bg_value} -tile 1x${nb_files} -geometry +40+10 ${FILES} \"$1\""

#echo "$MONTAGE_CMD"

eval "$MONTAGE_CMD"
