#!/usr/bin/env bash

if [ $# -gt 0 ]; then
	if [[ $1 = http* ]] || [[ $1 = *.mp4 ]]; then
		mpv $1 > /dev/null 2>&1 &
	else
		imv -r $1 > /dev/null 2>&1 & 
	fi
else
	imv -r ~/Pictures > /dev/null 2>&1 &
fi

